language: node_js
node_js:
  - "8"
  - "12"
  - "node"
deploy:
  provider: npm
  edge: true
  email: engineering-managers@wikimedia.de
  api_key:
    secure: gbc6m28GNh9fzEfiagbkhh5wjZ9sZxaKxQVHUfctGBMDGxL7fgmb9M2VDS37eEGpBrD3ZsPG1ROmEyDPW8w//j3Ss6QyDWRCK9H3UESvxAtTGPG+xuSZT0OkSCXs63UScFe9n7867Kln6tbP2ngs7IBkc40q/Hq8eLFT9nzAMxru2ISoHKbd5A9sb5hpPxhnhBlVw3b/nafZ5aoNczE9eKSNXwWuUJYpadMS4saBvxvvXzxUoQEZWYUhUIDGXWzc8c+g9mlkDqNYwjzVL2CJZFgGW0gM1dxuKen1J/8xJB7eDzxBv/ETKaF94CWGZg7+VSYhnWqciPAEWCKEm97RCcrp08B/bAf6vyCu3LHMP9/7Y89dsjirHHC2CIKi25ZwsuWG/ae1YArK4BeJ3f56OWUn+5g0c7A2scdbi3ciIW3Zv9Tfcm6P3QEnginEA4+W1eGF+NRd+GwX0KlwpjDbLATxxjtRNLR7ig87MD8OskABHzDCRGJfSz/x3k1ie2teYGef0t+U7an5vlv8+9hAHB8QdgO/YU22GpQ1JO6XKplDEOYECnTjsvbdnTYfW11/VmfwP9fGVqnCV0JYv/C+I7CooJeC3tamTYiCYpGepzqbnHGSX4osG8+0lrK/yJ/7fGYPqiUzHMByiErgFm2iPtKB/BpS0U4zTkRwCnCtsa8=
  on:
    tags: true
    branch: master
    condition: "$TRAVIS_NODE_VERSION = 12"
script:
  npm test
